### ISSUE TITLE
Wrong package used `sanity/structure` instead of `@sanity/structure`

### ISSUE THREAD

**Issue by tlazarov-whiskypartners** [sanity-io/sanity-plugin-documents-pane#64]
**Describe the bug**

The plugin tries to find `sanity/structure`, but the package is now named `@sanity/structure`.

**Which versions of Sanity are you using?**

^3.21.3

**What operating system are you using?**

MacOS

**Which versions of Node.js / npm are you running?**

10.2.4
v20.11.0

**Error message**

```
sanity:dev:   The plugin "vite:dep-pre-bundle" was triggered by this import
sanity:dev: 
sanity:dev:     ../../node_modules/.pnpm/sanity-plugin-utils@1.6.4_@sanity+ui@2.0.0_react-dom@18.2.0_react-fast-compare@3.2.2_react@18_dl6nsyrbpmk4iah6t67kasu2im/node_modules/sanity-plugin-utils/lib/index.esm.js:5:30:
sanity:dev:       5 │ import { usePaneRouter } from 'sanity/structure';
sanity:dev:         ╵                               ~~~~~~~~~~~~~~~~~~
sanity:dev: 
sanity:dev: 3:56:38 AM [vite] error while updating dependencies:
sanity:dev: Error: Build failed with 2 errors:
sanity:dev: ../../node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:21: ERROR: [plugin: vite:dep-pre-bundle] Missing "./structure" specifier in "sanity" package
sanity:dev: ../../node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:21: ERROR: [plugin: vite:dep-pre-bundle] Missing "./structure" specifier in "sanity" package
```

**Comment by SimeonGriggs** [comment]
Can't recreate the error.

Started a fresh Studio and installed this plugin without error.

Have you tried clearing node_modules and reinstalling all packages?

**Comment by apclarkk** [comment]
Experiencing identical issue with a fairly new studio install and after attempting to use [sanity-io/orderable-document-list](https://github.com/sanity-io/orderable-document-list). Cleared `node_modules` and reinstalled within no change :/ 
Any help would be appreciated ~
- Sanity: ^3.23.4
- Node: v20.9.0
- npm: 10.1.0
- Vite: ^5.0.8
- MacOS 13.5.1 

```
✘ [ERROR] Missing "./structure" specifier in "sanity" package [plugin vite:dep-pre-bundle]

    node_modules/@sanity/orderable-document-list/lib/index.esm.js:9:30:
      9 │ import { usePaneRouter } from 'sanity/structure';
        ╵                               ~~~~~~~~~~~~~~~~~~

✘ [ERROR] Missing "./structure" specifier in "sanity" package [plugin vite:dep-pre-bundle]

    node_modules/sanity-plugin-utils/lib/index.esm.js:5:30:
      5 │ import { usePaneRouter } from 'sanity/structure';
        ╵                               ~~~~~~~~~~~~~~~~~~

12:27:58 PM [vite] error while updating dependencies:
Error: Build failed with 2 errors:
node_modules/@sanity/orderable-document-list/lib/index.esm.js:9:30: ERROR: [plugin: vite:dep-pre-bundle] Missing "./structure" specifier in "sanity" package
node_modules/sanity-plugin-utils/lib/index.esm.js:5:30: ERROR: [plugin: vite:dep-pre-bundle] Missing "./structure" specifier in "sanity" package
    at failureErrorWithLog (/Users/apc/Documents/Coding/Hudons Cannabis/sanity/node_modules/vite/node_modules/esbuild/lib/main.js:1649:15)
    at /Users/apc/Documents/Coding/Hudons Cannabis/sanity/node_modules/vite/node_modules/esbuild/lib/main.js:1058:25
    at /Users/apc/Documents/Coding/Hudons Cannabis/sanity/node_modules/vite/node_modules/esbuild/lib/main.js:1525:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Jamiewarb** [comment]
Upgrading to the latest version of Sanity (3.29.1 at the time) fixed this for me. I was on 3.21.3, which pre-dates the internal migration to `sanity/structure`, and was therefore causing this error.

If you're getting this, check you're on Sanity version v3.24.1 or higher. This version marks the internal migration to `sanity/structure`

@apclarkk As you're on 3.23.4, you'll need to upgrade to at least 3.24.1

**Comment by apclarkk** [comment]
Will give this a try, thank you @Jamiewarb!
